### ISSUE TITLE
No way to know type from the contact list

### ISSUE THREAD

**Issue by DrRoux** [newatox/Elder.ly-ionic#122]
Hello, I'am big fan of your app. Me and my child use it everyday !!!!!

Is it possible for you to add a little image to tell the difference between a doctor, familly member and  senior in the list ? 

Thks

**Comment by nicolasvergoz** [comment]
Thanks for your review sir, we appreciate it.
And of course, we will indeed add this feature very soon.
Stay tuned ;)

**Comment by nicolasvergoz** [comment]
@DrRoux It's done sir.
Profile type in contact details 518ad9f72b8e422146269e1ed2e9cb3febe944c5
Profile type displayed in list 671cd52c30b278c58b96c4fd86c14914223573ea

 Thanks again for your feedback.
